[project]
name = "game"
version = "0.1.0"
dependencies = ["arcade"]

[project.optional-dependencies]
dev = ["nuitka"]

[project.scripts]
game = "game.cli:run"

[tool.setuptools.packages.find]
where = ["src"]

[build.system]
requires = ["setuptools>=65.5"]
build-backend = "setuptools.build_meta"
